name: Docker Image CI
on:
  push:
    paths:
        - ".devcontainer/Dockerfile"
        - ".github/**"
    branches: [master]
  pull_request:
    paths:
        - ".devcontainer/Dockerfile"
        - ".github/**"
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        ghc: ["9.0.2"]
        stack: ["2.7.5"]
        resolver: ["lts-19.16"]
        cabal: ["3.6.3.0"]
        hls: ["1.7.0.0"]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./.devcontainer/ --file ./.devcontainer/Dockerfile --build-arg GHC_VERSION=${{ matrix.ghc }} --build-arg STACK_RESOLVER=${{ matrix.resolver }} --build-arg STACK_VERSION=${{ matrix.stack }} --build-arg CABAL_VERSION=${{ matrix.cabal }} --build-arg HLS_VERSION=${{ matrix.hls }} --tag vlza/haskelldevenv:${{ matrix.ghc }}-${{ matrix.resolver }}-${{ matrix.resolver }}-$(date +%s)
